"""rag

Revision ID: 778951e24058
Revises: 893f07fc924c
Create Date: 2026-04-21 09:15:32.549681
Feature:
Reason:

"""

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "778951e24058"
down_revision: Union[str, Sequence[str], None] = "893f07fc924c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "Rag"')
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_textsearch")

    op.create_table(
        "Metadata",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["FileStorage.Files.id"],
            name=op.f("Metadata_file_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("Metadata_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Metadata_pkey")),
        sa.UniqueConstraint("file_id", name=op.f("Metadata_file_id_uq")),
        schema="Rag",
    )
    op.create_index(
        op.f("Metadata_project_id_idx"),
        "Metadata",
        ["project_id"],
        unique=False,
        schema="Rag",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("Metadata_project_id_idx"), table_name="Metadata", schema="Rag"
    )
    op.drop_table("Metadata", schema="Rag")
    # ### end Alembic commands ###
    op.execute('DROP SCHEMA "Rag"')
