import os


GOOGLE_PROGRAMMATIC_SEARCH_API_KEY = os.environ[
    "GOOGLE_PROGRAMMABLE_SEARCH_API_KEY"
]
GOOGLE_PROGRAMMATIC_SEARCH_CX = os.environ["GOOGLE_PROGRAMMABLE_SEARCH_CX"]

CRAWLER_MAX_CONCURRENT = int(os.environ.get("CRAWLER_MAX_CONCURRENT", "8"))
