repos:
  - repo: local
    hooks:
      - id: tidy
        name: Format & sort imports
        entry: ./scripts/tidy.sh
        language: script
        files: ^.*\.py$

      - id: update-example-env-files
        name: Update example.env files
        entry: ./scripts/gen-example-env.sh
        language: script
        always_run: true
        files: ^$
