repos:
  - repo: local
    hooks:
      - id: tidy
        name: Format & sort imports
        entry: sh -c "./scripts/tidy.sh"
        language: system
        files: ^.*\.py$

      - id: update-example-env-files
        name: Update example.env files
        entry: uv run examplenv gen
        language: system
        always_run: true
        files: ^$
