services:
  db:
    image: pgvector/pgvector:pg18
    container_name: postgres-pgvector
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      # /var/lib/postgresql/data to /var/lib/postgresql: https://github.com/docker-library/postgres/pull/1259
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: sh -c "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env.redis
    volumes:
      - redis_data:/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env.pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: