services:
  db:
    image: pgvector/pgvector:pg18
    container_name: postgres-pgvector
    env_file:
      - .env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U internet_crawler -d tailm"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - db_network

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - redis_network
  
  main:
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - prod.env
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    pull_policy: always # Ensures compose always tries to pull a new image
    networks:
      - db_network
      - redis_network

network:
  db_network:
  redis_network:

volumes:
  postgres_data: