[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi[standard]>=0.116.1",
    "numpy>=2.3.3",
    "orjson>=3.11.3",
    "pandas>=2.3.2",
    "psycopg2-binary>=2.9.10",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.43",
    "structlog>=25.4.0",
]

[tool.black]
line-length = 80
include = '\.pyi?$'
exclude = '''
/(
    | .*__pycache__.*
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[project.entry-points.pydantic]
observe = "plugins:plugins:plugin"

[tool.pyright]
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportTypedDictNotRequiredAccess = false
# reportIncompatibleMethodOverride = false
# reportGeneralTypeIssues = false
exclude = ["*.pyi?$", "*__pycache__*", "venv"]

[dependency-groups]
dev = ["black>=25.1.0", "flake8>=7.3.0", "ipython>=9.5.0"]
