"""rerank

Revision ID: 19f77192d356
Revises: b9a6c6eab6dc
Create Date: 2026-05-22 07:57:53.543885
Feature:
Reason:

"""
from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19f77192d356'
down_revision: Union[str, Sequence[str], None] = 'b9a6c6eab6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent

def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("""CREATE EXTENSION IF NOT EXISTS pg_textsearch;""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # # ### end Alembic commands ###
    # op.execute("""DROP EXTENSION IF EXISTS pg_textsearch;""")
