"""Combined

Revision ID: 893f07fc924c
Revises:
Create Date: 2026-04-23 21:02:05.630776
Feature:
Reason:

"""

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "893f07fc924c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    schemas = [
        "Organization",
        "Project",
        "ApiKey",
        "Conversation",
        "FileStorage",
        "Billing",
    ]
    for schema in schemas:
        op.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))
    op.create_table(
        "DeletionRequests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("DeletionRequests_pkey")),
        schema="Organization",
    )
    op.create_index(
        op.f("DeletionRequests_org_id_idx"),
        "DeletionRequests",
        ["org_id"],
        unique=True,
        schema="Organization",
    )
    op.create_table(
        "Settings",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("spending_limit", sa.BigInteger(), nullable=True),
        sa.Column("extra", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("org_id", name=op.f("Settings_pkey")),
        schema="Organization",
    )
    op.create_table(
        "Projects",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column(
            "is_archived", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Projects_pkey")),
        schema="Project",
    )
    op.create_index(
        op.f("Projects_organization_id_idx"),
        "Projects",
        ["organization_id"],
        unique=False,
        schema="Project",
    )
    op.create_index(
        op.f("Projects_uuid_idx"),
        "Projects",
        ["uuid"],
        unique=True,
        schema="Project",
    )
    op.create_table(
        "ApiKeys",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("hint", sa.String(length=128), nullable=False),
        sa.Column("hashed_key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=False),
        sa.Column(
            "permissions",
            postgresql.ARRAY(sa.String(length=1024)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "disabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("ApiKeys_project_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ApiKeys_pkey")),
        schema="ApiKey",
    )
    op.create_index(
        op.f("ApiKeys_hashed_key_idx"),
        "ApiKeys",
        ["hashed_key"],
        unique=True,
        schema="ApiKey",
    )
    op.create_index(
        op.f("ApiKeys_project_id_idx"),
        "ApiKeys",
        ["project_id"],
        unique=False,
        schema="ApiKey",
    )
    op.create_table(
        "Conversations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "extra_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("Conversations_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Conversations_pkey")),
        schema="Conversation",
    )
    op.create_index(
        op.f("Conversations_project_id_idx"),
        "Conversations",
        ["project_id"],
        unique=False,
        schema="Conversation",
    )
    op.create_index(
        op.f("Conversations_uuid_idx"),
        "Conversations",
        ["uuid"],
        unique=True,
        schema="Conversation",
    )
    op.create_table(
        "Files",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=256), nullable=False),
        sa.Column("filepath", sa.String(length=512), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("size_in_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADING",
                "AVAILABLE",
                "DELETED",
                name="filestatus",
                schema="FileStorage",
            ),
            nullable=False,
        ),
        sa.Column(
            "extra_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("Files_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Files_pkey")),
        schema="FileStorage",
    )
    op.create_index(
        op.f("Files_project_id_idx"),
        "Files",
        ["project_id"],
        unique=False,
        schema="FileStorage",
    )
    op.create_index(
        op.f("Files_uuid_idx"),
        "Files",
        ["uuid"],
        unique=True,
        schema="FileStorage",
    )
    op.create_table(
        "ProjectMembers",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("ProjectMembers_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "user_id", name=op.f("ProjectMembers_pkey")
        ),
        schema="Project",
    )
    op.create_table(
        "Settings",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("spending_limit", sa.BigInteger(), nullable=True),
        sa.Column("extra", sa.JSON(), server_default="{}", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("Settings_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("Settings_pkey")),
        schema="Project",
    )
    op.create_table(
        "Messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "seq_id",
            sa.BigInteger(),
            server_default=sa.FetchedValue(),
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=32), nullable=True),
        sa.Column(
            "parts", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("model_name", sa.String(length=32), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["Conversation.Conversations.id"],
            name=op.f("Messages_conversation_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Messages_pkey")),
        schema="Conversation",
    )
    op.create_index(
        op.f("Messages_conversation_id_idx"),
        "Messages",
        ["conversation_id"],
        unique=False,
        schema="Conversation",
    )
    op.create_index(
        op.f("Messages_seq_id_idx"),
        "Messages",
        ["seq_id"],
        unique=False,
        schema="Conversation",
    )
    op.create_index(
        op.f("Messages_uuid_idx"),
        "Messages",
        ["uuid"],
        unique=True,
        schema="Conversation",
    )
    op.create_table(
        "BillingInvoices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("billing_period", sa.Date(), nullable=False),
        sa.Column(
            "total_amount", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "provider",
            sa.Enum("STRIPE", "PAYPAL", name="billingsourceprovider"),
            nullable=True,
        ),
        sa.Column("provider_invoice_id", sa.String(length=128), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("refunded_at", sa.DateTime(), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "used_credits", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("BillingInvoices_pkey")),
        sa.UniqueConstraint(
            "organization_id", "billing_period", name="uq_org_billing_period"
        ),
        sa.UniqueConstraint(
            "provider", "provider_invoice_id", name="uq_provider_invoice"
        ),
        schema="Billing",
    )
    op.create_index(
        op.f("BillingInvoices_organization_id_idx"),
        "BillingInvoices",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingInvoices_uuid_idx"),
        "BillingInvoices",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    op.create_table(
        "BillingSources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("STRIPE", "PAYPAL", name="billingsourceprovider"),
            nullable=False,
        ),
        sa.Column("provider_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("BillingSources_pkey")),
        schema="Billing",
    )
    op.create_index(
        op.f("BillingSources_organization_id_idx"),
        "BillingSources",
        ["organization_id"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingSources_uuid_idx"),
        "BillingSources",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    op.create_table(
        "BillingTransactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("apikey_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CAPTURED", "EXPIRED", name="transactionstatus"),
            nullable=False,
        ),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "id", "created_at", name=op.f("BillingTransactions_pkey")
        ),
        schema="Billing",
    )
    op.create_index(
        op.f("BillingTransactions_apikey_id_idx"),
        "BillingTransactions",
        ["apikey_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingTransactions_organization_id_idx"),
        "BillingTransactions",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingTransactions_project_id_idx"),
        "BillingTransactions",
        ["project_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingTransactions_status_idx"),
        "BillingTransactions",
        ["status"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingTransactions_uuid_idx"),
        "BillingTransactions",
        ["uuid"],
        unique=False,
        schema="Billing",
    )
    op.create_table(
        "CreditTransactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("CreditTransactions_pkey")),
        schema="Billing",
    )
    op.create_index(
        op.f("CreditTransactions_organization_id_idx"),
        "CreditTransactions",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.create_table(
        "Credits",
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("organization_id", name=op.f("Credits_pkey")),
        schema="Billing",
    )
    op.create_index(
        op.f("Credits_organization_id_idx"),
        "Credits",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.create_table(
        "SpendingLimits",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "limit_type",
            sa.Enum("MONTHLY", name="spendinglimittype", schema="Billing"),
            nullable=False,
        ),
        sa.Column("limit", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("SpendingLimits_pkey")),
        sa.UniqueConstraint(
            "organization_id", "project_id", name="uq_spending_limit"
        ),
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_organization_id_idx"),
        "SpendingLimits",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_project_id_idx"),
        "SpendingLimits",
        ["project_id"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_uuid_idx"),
        "SpendingLimits",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        "ix_spending_limits_org",
        "SpendingLimits",
        ["organization_id"],
        unique=True,
        schema="Billing",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    # op.create_table(
    #     "daily_billing_summary",
    #     sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
    #     sa.Column("organization_id", sa.String(), nullable=False),
    #     sa.Column("project_id", sa.BigInteger(), nullable=False),
    #     sa.Column("apikey_id", sa.BigInteger(), nullable=False),
    #     sa.Column("total_amount", sa.Numeric(), nullable=False),
    #     sa.Column("transaction_count", sa.BigInteger(), nullable=False),
    #     sa.PrimaryKeyConstraint(
    #         "bucket",
    #         "organization_id",
    #         "project_id",
    #         "apikey_id",
    #         name=op.f("daily_billing_summary_pkey"),
    #     ),
    #     schema="Billing",
    #     skip_autogenerate=True,
    # )
    op.create_table(
        "BillingInvoiceLineItems",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["Billing.BillingInvoices.id"],
            name=op.f("BillingInvoiceLineItems_invoice_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("BillingInvoiceLineItems_pkey")
        ),
        schema="Billing",
    )
    op.create_index(
        op.f("BillingInvoiceLineItems_invoice_id_idx"),
        "BillingInvoiceLineItems",
        ["invoice_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingInvoiceLineItems_project_id_idx"),
        "BillingInvoiceLineItems",
        ["project_id"],
        unique=False,
        schema="Billing",
    )
    op.create_index(
        op.f("BillingInvoiceLineItems_uuid_idx"),
        "BillingInvoiceLineItems",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    # ### end Alembic commands ###
    op.execute("""SELECT create_hypertable (
        '"Billing"."BillingTransactions"', 'created_at', chunk_time_interval => INTERVAL '7 days'
    )""")
    op.execute("""ALTER TABLE "Billing"."BillingTransactions" SET (
        timescaledb.compress,
        timescaledb.compress_segmentby = 'apikey_id, project_id, organization_id',
        timescaledb.compress_orderby = 'created_at DESC'
    );""")
    op.execute("""SELECT add_compression_policy (
        '"Billing"."BillingTransactions"', INTERVAL '14 days'
    );""")
    op.execute("""CREATE MATERIALIZED VIEW "Billing".daily_billing_summary
        WITH (timescaledb.continuous) AS
        SELECT
            time_bucket ('1 day', created_at) AS bucket,
            apikey_id,
            project_id,
            organization_id,
            SUM(amount) FILTER (
                WHERE
                    status IN ('CAPTURED', 'PENDING')
            ) AS total_amount,
            COUNT(*) AS transaction_count
        FROM "Billing"."BillingTransactions"
        GROUP BY
            bucket,
            apikey_id,
            project_id,
            organization_id
        with
            no data;""")

    op.execute("""ALTER MATERIALIZED VIEW "Billing".daily_billing_summary
        SET (
            timescaledb.materialized_only = false
        );""")
    op.execute("""SELECT add_continuous_aggregate_policy (
        '"Billing".daily_billing_summary',
        start_offset => INTERVAL '3 days',
        end_offset => INTERVAL '0 seconds',
        schedule_interval => INTERVAL '1 hour'
    );""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("BillingInvoiceLineItems_uuid_idx"),
        table_name="BillingInvoiceLineItems",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingInvoiceLineItems_project_id_idx"),
        table_name="BillingInvoiceLineItems",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingInvoiceLineItems_invoice_id_idx"),
        table_name="BillingInvoiceLineItems",
        schema="Billing",
    )
    op.drop_table("BillingInvoiceLineItems", schema="Billing")
    op.drop_table("daily_billing_summary", schema="Billing")
    op.drop_index(
        "ix_spending_limits_org",
        table_name="SpendingLimits",
        schema="Billing",
        postgresql_where=sa.text("project_id IS NULL"),
    )
    op.drop_index(
        op.f("SpendingLimits_uuid_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("SpendingLimits_project_id_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("SpendingLimits_organization_id_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_table("SpendingLimits", schema="Billing")
    op.drop_index(
        op.f("Credits_organization_id_idx"),
        table_name="Credits",
        schema="Billing",
    )
    op.drop_table("Credits", schema="Billing")
    op.drop_index(
        op.f("CreditTransactions_organization_id_idx"),
        table_name="CreditTransactions",
        schema="Billing",
    )
    op.drop_table("CreditTransactions", schema="Billing")
    op.drop_index(
        op.f("BillingTransactions_uuid_idx"),
        table_name="BillingTransactions",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingTransactions_status_idx"),
        table_name="BillingTransactions",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingTransactions_project_id_idx"),
        table_name="BillingTransactions",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingTransactions_organization_id_idx"),
        table_name="BillingTransactions",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingTransactions_apikey_id_idx"),
        table_name="BillingTransactions",
        schema="Billing",
    )
    op.drop_table("BillingTransactions", schema="Billing")
    op.drop_index(
        op.f("BillingSources_uuid_idx"),
        table_name="BillingSources",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingSources_organization_id_idx"),
        table_name="BillingSources",
        schema="Billing",
    )
    op.drop_table("BillingSources", schema="Billing")
    op.drop_index(
        op.f("BillingInvoices_uuid_idx"),
        table_name="BillingInvoices",
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingInvoices_organization_id_idx"),
        table_name="BillingInvoices",
        schema="Billing",
    )
    op.drop_table("BillingInvoices", schema="Billing")
    op.drop_index(
        op.f("Messages_uuid_idx"), table_name="Messages", schema="Conversation"
    )
    op.drop_index(
        op.f("Messages_seq_id_idx"),
        table_name="Messages",
        schema="Conversation",
    )
    op.drop_index(
        op.f("Messages_conversation_id_idx"),
        table_name="Messages",
        schema="Conversation",
    )
    op.drop_table("Messages", schema="Conversation")
    op.drop_table("Settings", schema="Project")
    op.drop_table("ProjectMembers", schema="Project")
    op.drop_index(
        op.f("Files_uuid_idx"), table_name="Files", schema="FileStorage"
    )
    op.drop_index(
        op.f("Files_project_id_idx"), table_name="Files", schema="FileStorage"
    )
    op.drop_table("Files", schema="FileStorage")
    op.drop_index(
        op.f("Conversations_uuid_idx"),
        table_name="Conversations",
        schema="Conversation",
    )
    op.drop_index(
        op.f("Conversations_project_id_idx"),
        table_name="Conversations",
        schema="Conversation",
    )
    op.drop_table("Conversations", schema="Conversation")
    op.drop_index(
        op.f("ApiKeys_project_id_idx"), table_name="ApiKeys", schema="ApiKey"
    )
    op.drop_index(
        op.f("ApiKeys_hashed_key_idx"), table_name="ApiKeys", schema="ApiKey"
    )
    op.drop_table("ApiKeys", schema="ApiKey")
    op.drop_index(
        op.f("Projects_uuid_idx"), table_name="Projects", schema="Project"
    )
    op.drop_index(
        op.f("Projects_organization_id_idx"),
        table_name="Projects",
        schema="Project",
    )
    op.drop_table("Projects", schema="Project")
    op.drop_table("Settings", schema="Organization")
    op.drop_index(
        op.f("DeletionRequests_org_id_idx"),
        table_name="DeletionRequests",
        schema="Organization",
    )
    op.drop_table("DeletionRequests", schema="Organization")
    schemas = [
        "Billing",
        "FileStorage",
        "Conversation",
        "ApiKey",
        "Project",
        "Organization",
    ]
    op.execute(
        'DROP MATERIALIZED VIEW IF EXISTS "Billing".daily_billing_summary'
    )
    for schema in schemas:
        op.execute(sa.text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))
    # ### end Alembic commands ###
