"""conversation

Revision ID: b9a6c6eab6dc
Revises: d54c4d8cb29e
Create Date: 2026-05-19 15:53:30.446960
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9a6c6eab6dc"
down_revision: Union[str, Sequence[str], None] = "d54c4d8cb29e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ApiKeys",
        "permissions",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String(length=1024)),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::text[]"),
        schema="ApiKey",
    )
    op.execute(
        "CREATE TYPE \"Conversation\".conversationtype AS ENUM ('SEQUENCE', 'TREE');"
    )
    op.add_column(
        "Conversations",
        sa.Column(
            "conversation_type",
            sa.Enum(
                "SEQUENCE",
                "TREE",
                name="conversationtype",
                schema="Conversation",
            ),
            server_default="SEQUENCE",
            nullable=False,
        ),
        schema="Conversation",
    )
    op.add_column(
        "Conversations",
        sa.Column(
            "tree_structure",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        schema="Conversation",
    )
    op.add_column(
        "Conversations",
        sa.Column("active_leaf_message_id", sa.UUID(), nullable=True),
        schema="Conversation",
    )
    op.add_column(
        "Conversations",
        sa.Column(
            "relationships_map",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        schema="Conversation",
    )
    op.add_column(
        "Messages",
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        schema="Conversation",
    )
    op.add_column(
        "Messages",
        sa.Column(
            "extra_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        schema="Conversation",
    )
    op.drop_index(
        op.f("Messages_seq_id_idx"),
        table_name="Messages",
        schema="Conversation",
    )
    op.drop_index(
        op.f("Messages_uuid_idx"), table_name="Messages", schema="Conversation"
    )
    op.create_index(
        op.f("Messages_uuid_idx"),
        "Messages",
        ["uuid"],
        unique=True,
        schema="Conversation",
    )
    op.drop_column("Messages", "model_name", schema="Conversation")
    op.drop_column("Messages", "parts", schema="Conversation")
    op.drop_column("Messages", "kind", schema="Conversation")
    op.drop_column("Messages", "seq_id", schema="Conversation")
    op.alter_column(
        "Files",
        "mime_type",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
        schema="FileStorage",
    )
    # op.drop_index(op.f('ProjectMembers_user_id_idx'), table_name='ProjectMembers', schema='Project')
    op.alter_column(
        "Projects",
        "organization_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=128),
        existing_nullable=False,
        schema="Project",
    )
    op.alter_column(
        "Projects",
        "is_archived",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
        schema="Project",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Projects",
        "is_archived",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
        schema="Project",
    )
    op.alter_column(
        "Projects",
        "organization_id",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        schema="Project",
    )
    # op.create_index(
    #     op.f("ProjectMembers_user_id_idx"),
    #     "ProjectMembers",
    #     ["user_id"],
    #     unique=False,
    #     schema="Project",
    # )
    op.alter_column(
        "Files",
        "mime_type",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
        schema="FileStorage",
    )
    op.add_column(
        "Messages",
        sa.Column("seq_id", sa.BIGINT(), autoincrement=False, nullable=False),
        schema="Conversation",
    )
    op.add_column(
        "Messages",
        sa.Column(
            "kind", sa.VARCHAR(length=32), autoincrement=False, nullable=True
        ),
        schema="Conversation",
    )
    op.add_column(
        "Messages",
        sa.Column(
            "parts",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        schema="Conversation",
    )
    op.add_column(
        "Messages",
        sa.Column(
            "model_name",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
        schema="Conversation",
    )
    op.drop_index(
        op.f("Messages_uuid_idx"), table_name="Messages", schema="Conversation"
    )
    op.create_index(
        op.f("Messages_uuid_idx"),
        "Messages",
        ["uuid"],
        unique=False,
        schema="Conversation",
    )
    op.create_index(
        op.f("Messages_seq_id_idx"),
        "Messages",
        ["seq_id"],
        unique=False,
        schema="Conversation",
    )
    op.drop_column("Messages", "extra_metadata", schema="Conversation")
    op.drop_column("Messages", "payload", schema="Conversation")
    op.drop_column("Conversations", "relationships_map", schema="Conversation")
    op.drop_column(
        "Conversations", "active_leaf_message_id", schema="Conversation"
    )
    op.drop_column("Conversations", "tree_structure", schema="Conversation")
    op.drop_column("Conversations", "conversation_type", schema="Conversation")
    op.alter_column(
        "ApiKeys",
        "permissions",
        existing_type=postgresql.ARRAY(sa.String(length=1024)),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::text[]"),
        schema="ApiKey",
    )
    # ### end Alembic commands ###
