"""Add UUID to ApiKey

Revision ID: d54c4d8cb29e
Revises: 778951e24058
Create Date: 2026-05-03 16:47:32.333318
Feature:
Reason:

"""

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "d54c4d8cb29e"
down_revision: Union[str, Sequence[str], None] = "778951e24058"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("SpendingLimits_organization_id_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("SpendingLimits_project_id_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("SpendingLimits_uuid_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("ix_spending_limits_org"),
        table_name="SpendingLimits",
        schema="Billing",
        postgresql_where="(project_id IS NULL)",
    )
    op.drop_table("SpendingLimits", schema="Billing")
    op.add_column(
        "ApiKeys", sa.Column("uuid", sa.Uuid(), nullable=False), schema="ApiKey"
    )
    op.create_index(
        op.f("ApiKeys_uuid_idx"),
        "ApiKeys",
        ["uuid"],
        unique=True,
        schema="ApiKey",
    )
    op.alter_column(
        "Settings",
        "extra",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
        schema="Organization",
    )
    op.alter_column(
        "Settings",
        "extra",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
        schema="Project",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "Settings",
        "extra",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
        schema="Project",
    )
    op.alter_column(
        "Settings",
        "extra",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),
        schema="Organization",
    )
    op.drop_index(
        op.f("ApiKeys_uuid_idx"), table_name="ApiKeys", schema="ApiKey"
    )
    op.drop_column("ApiKeys", "uuid", schema="ApiKey")
    op.create_table(
        "SpendingLimits",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "organization_id",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "project_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "limit_type",
            postgresql.ENUM(
                "MONTHLY", name="spendinglimittype", schema="Billing"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "limit",
            sa.NUMERIC(precision=18, scale=8),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("SpendingLimits_pkey")),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            name=op.f("uq_spending_limit"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema="Billing",
    )
    op.create_index(
        op.f("ix_spending_limits_org"),
        "SpendingLimits",
        ["organization_id"],
        unique=True,
        schema="Billing",
        postgresql_where="(project_id IS NULL)",
    )
    op.create_index(
        op.f("SpendingLimits_uuid_idx"),
        "SpendingLimits",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_project_id_idx"),
        "SpendingLimits",
        ["project_id"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_organization_id_idx"),
        "SpendingLimits",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    # ### end Alembic commands ###
