events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 3000;
        server_name localhost;

        root /var/www/user-dashboard;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 5173;
        server_name localhost;

        root /var/www/admin-dashboard;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
