"""conversation_message_update

Revision ID: 0091936a904e
Revises: 6dfe5f2fd7ff
Create Date: 2026-01-26 09:56:46.340381
Feature:
Reason:

"""
from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0091936a904e'
down_revision: Union[str, Sequence[str], None] = '6dfe5f2fd7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent

def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")

def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "0091936a904e_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Messages', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Text(),
               existing_nullable=True,
               schema='Conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "0091936a904e_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Messages', 'timestamp',
               existing_type=sa.Text(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='Conversation')
    # ### end Alembic commands ###
