"""auth

Revision ID: 13faff8bbad8
Revises: 2669f293a37f
Create Date: 2025-11-27 16:38:46.617603
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13faff8bbad8"
down_revision: Union[str, Sequence[str], None] = "2669f293a37f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS app;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "PERMISSIONS",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
        schema="app",
    )
    op.create_table(
        "USERS",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="app",
    )
    op.create_table(
        "API_KEYS",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("hashed_key", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app.USERS.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_key"),
        sa.UniqueConstraint("id"),
        schema="app",
    )
    op.create_table(
        "API_KEY_PERMISSIONS",
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("permission_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["app.API_KEYS.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_name"],
            ["app.PERMISSIONS.name"],
        ),
        sa.PrimaryKeyConstraint("api_key_id", "permission_name"),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("API_KEY_PERMISSIONS", schema="app")
    op.drop_table("API_KEYS", schema="app")
    op.drop_table("USERS", schema="app")
    op.drop_table("PERMISSIONS", schema="app")
    op.execute("DROP SCHEMA IF EXISTS app CASCADE;")
    # ### end Alembic commands ###
