"""message

Revision ID: 23c4153d35e9
Revises: 2abf94d9e843
Create Date: 2026-02-27 17:38:11.940879
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "23c4153d35e9"
down_revision: Union[str, Sequence[str], None] = "2abf94d9e843"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "23c4153d35e9_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Messages",
        sa.Column("seq_id", sa.BigInteger(), nullable=False),
        schema="Conversation",
    )
    op.alter_column(
        "Messages",
        "conversation_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        schema="Conversation",
    )
    op.create_index(
        op.f("Messages_conversation_id_idx"),
        "Messages",
        ["conversation_id"],
        unique=False,
        schema="Conversation",
    )
    op.create_index(
        op.f("Messages_seq_id_idx"),
        "Messages",
        ["seq_id"],
        unique=False,
        schema="Conversation",
    )
    op.create_foreign_key(
        op.f("Messages_conversation_id_fkey"),
        "Messages",
        "Conversations",
        ["conversation_id"],
        ["id"],
        source_schema="Conversation",
        referent_schema="Conversation",
    )
    op.execute(
        text("""
    CREATE OR REPLACE FUNCTION generate_msg_seq()
RETURNS TRIGGER AS $$
BEGIN
    SELECT COALESCE(MAX(seq_id), 0) + 1
    INTO NEW.seq_id
    FROM "Conversation"."Messages"
    WHERE conversation_id = NEW.conversation_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
                    """)
    )
    op.execute(
        text("""
CREATE TRIGGER trg_msg_seq
BEFORE INSERT ON "Conversation"."Messages"
FOR EACH ROW EXECUTE FUNCTION generate_msg_seq();""")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "23c4153d35e9_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("Messages_conversation_id_fkey"),
        "Messages",
        schema="Conversation",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("Messages_seq_id_idx"),
        table_name="Messages",
        schema="Conversation",
    )
    op.drop_index(
        op.f("Messages_conversation_id_idx"),
        table_name="Messages",
        schema="Conversation",
    )
    op.alter_column(
        "Messages",
        "conversation_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        schema="Conversation",
    )
    op.drop_column("Messages", "seq_id", schema="Conversation")
    # ### end Alembic commands ###
