"""auth

Revision ID: 2669f293a37f
Revises: f42d1171c815
Create Date: 2025-11-18 08:19:50.024727
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2669f293a37f"
down_revision: Union[str, Sequence[str], None] = "f42d1171c815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def upgrade() -> None:
    """Upgrade schema."""
    # with open(script_directory / "2669f293a37f_upgrade.sql") as f:
    #     sql = f.read()
    # op.execute(sql)
    op.execute("CREATE SCHEMA IF NOT EXISTS app")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name"),
        schema="app",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
        schema="app",
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hashed_key", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, default=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_key"),
        sa.UniqueConstraint("id"),
        schema="app",
    )
    op.create_table(
        "api_key_permissions",
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("permission_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["app.api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_name"],
            ["app.permissions.name"],
        ),
        sa.PrimaryKeyConstraint("api_key_id", "permission_name"),
        schema="app",
    )
    # op.drop_index(op.f('idx_conversations_conversation_id'), table_name='conversations')
    # op.drop_index(op.f('idx_conversations_updated_at'), table_name='conversations')
    # op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    # op.drop_table('conversations')
    # op.drop_table('ai_providers')
    # op.drop_index(op.f('idx_messages_conversation_pk'), table_name='messages')
    # op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    # op.drop_table('messages')
    # op.drop_index(op.f('idx_base_ai_models_name'), table_name='base_ai_models')
    # op.drop_table('base_ai_models')
    # op.drop_index(op.f('idx_message_parts_messages_pk'), table_name='message_parts')
    # op.drop_table('message_parts')
    # op.drop_table('message_roles')
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_table('users')
    # op.drop_table('message_citation_types')
    # op.drop_index(op.f('idx_ai_models_user_id_name'), table_name='ai_models')
    # op.drop_table('ai_models')
    # op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    # op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    # op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    # op.drop_table('api_keys')
    # op.drop_index(op.f('idx_message_citations_messages_pk'), table_name='message_citations')
    # op.drop_table('message_citations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # with open(script_directory / "2669f293a37f_downgrade.sql") as f:
    #     sql = f.read()
    # op.execute(sql)
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('message_citations',
    # sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('message_pk', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('start_index', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('end_index', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('reference_type_pk', sa.SMALLINT(), server_default=sa.text("nextval('message_citations_reference_type_pk_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('title', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    # sa.Column('src', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    # sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['message_pk'], ['messages.pk'], name=op.f('message_citations_message_pk_fkey')),
    # sa.ForeignKeyConstraint(['reference_type_pk'], ['message_citation_types.pk'], name=op.f('message_citations_reference_type_pk_fkey'), onupdate='CASCADE'),
    # sa.PrimaryKeyConstraint('pk', name=op.f('message_citations_pkey'))
    # )
    # op.create_index(op.f('idx_message_citations_messages_pk'), 'message_citations', ['message_pk'], unique=False)
    # op.create_table('api_keys',
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    # sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('api_keys_user_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey')),
    # sa.UniqueConstraint('api_key', name=op.f('api_keys_api_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    # op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=False)
    # op.create_table('ai_models',
    # sa.Column('pk', sa.INTEGER(), server_default=sa.text("nextval('ai_models_pk_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('base_ai_model_pk', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('instruction', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['base_ai_model_pk'], ['base_ai_models.pk'], name='ai_models_base_ai_model_pk_fkey'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_models_user_id_fkey'),
    # sa.PrimaryKeyConstraint('pk', name='ai_models_pkey'),
    # sa.UniqueConstraint('name', name='ai_models_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # sa.UniqueConstraint('user_id', 'name', name='constraint_ai_models_user_id_name_unique', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index(op.f('idx_ai_models_user_id_name'), 'ai_models', ['user_id', 'name'], unique=False)
    # op.create_table('message_citation_types',
    # sa.Column('pk', sa.SMALLINT(), server_default=sa.text("nextval('message_citation_types_pk_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('reference_type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('pk', name=op.f('message_citation_types_pkey')),
    # sa.UniqueConstraint('reference_type', name=op.f('message_citation_types_reference_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_table('users',
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='users_pkey'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_table('message_roles',
    # sa.Column('pk', sa.SMALLINT(), server_default=sa.text("nextval('message_roles_pk_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('role', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('pk', name='message_roles_pkey'),
    # sa.UniqueConstraint('role', name='message_roles_role_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('message_parts',
    # sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('message_pk', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('index', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['message_pk'], ['messages.pk'], name=op.f('message_parts_message_pk_fkey'), onupdate='CASCADE'),
    # sa.PrimaryKeyConstraint('pk', name=op.f('message_parts_pkey')),
    # sa.UniqueConstraint('message_pk', 'file_name', name=op.f('constraint_uq_message_parts_message_pk_file_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_index(op.f('idx_message_parts_messages_pk'), 'message_parts', ['message_pk'], unique=False)
    # op.create_table('base_ai_models',
    # sa.Column('pk', sa.SMALLINT(), server_default=sa.text("nextval('base_ai_models_pk_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('provider_pk', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('model_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('rate_per_sec', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['provider_pk'], ['ai_providers.pk'], name='base_ai_models_provider_pk_fkey'),
    # sa.PrimaryKeyConstraint('pk', name='base_ai_models_pkey'),
    # sa.UniqueConstraint('name', name='base_ai_models_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_index(op.f('idx_base_ai_models_name'), 'base_ai_models', ['name'], unique=False)
    # op.create_table('messages',
    # sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    # sa.Column('conversation_pk', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('ai_model_pk', sa.BIGINT(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('role_pk', sa.SMALLINT(), autoincrement=False, nullable=False),
    # sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('tool_call', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['ai_model_pk'], ['ai_models.pk'], name=op.f('messages_ai_model_pk_fkey')),
    # sa.ForeignKeyConstraint(['conversation_pk'], ['conversations.pk'], name=op.f('messages_conversation_pk_fkey')),
    # sa.ForeignKeyConstraint(['role_pk'], ['message_roles.pk'], name=op.f('messages_role_pk_fkey')),
    # sa.PrimaryKeyConstraint('pk', name=op.f('messages_pkey')),
    # sa.UniqueConstraint('id', name=op.f('messages_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_index(op.f('idx_messages_created_at'), 'messages', [sa.literal_column('created_at DESC')], unique=False)
    # op.create_index(op.f('idx_messages_conversation_pk'), 'messages', ['conversation_pk'], unique=False)
    # op.create_table('ai_providers',
    # sa.Column('pk', sa.SMALLINT(), server_default=sa.text("nextval('ai_providers_pk_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('pk', name=op.f('ai_providers_pkey'))
    # )
    # op.create_table('conversations',
    # sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False, comment='Key-value string pairs. Application-level limits: 16 pairs, max key length 64, max value length 512.'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey')),
    # sa.PrimaryKeyConstraint('pk', name=op.f('conversations_pkey')),
    # sa.UniqueConstraint('id', name=op.f('conversations_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # op.create_index(op.f('idx_conversations_updated_at'), 'conversations', [sa.literal_column('updated_at DESC')], unique=False)
    # op.create_index(op.f('idx_conversations_conversation_id'), 'conversations', ['id'], unique=False)
    op.drop_table("api_key_permissions", schema="app")
    op.drop_table("api_keys", schema="app")
    op.drop_table("users", schema="app")
    op.drop_table("permissions", schema="app")
    op.execute("DROP SCHEMA IF EXISTS app CASCADE")
    # ### end Alembic commands ###
