"""billing

Revision ID: 27e4b090ceec
Revises: 7dbe206afcb5
Create Date: 2026-04-11 15:36:59.729058
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "27e4b090ceec"
down_revision: Union[str, Sequence[str], None] = "7dbe206afcb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "27e4b090ceec_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "CreditTransactions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("CreditTransactions_pkey")),
        schema="Billing",
    )
    op.create_index(
        op.f("CreditTransactions_organization_id_idx"),
        "CreditTransactions",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.add_column(
        "BillingInvoices",
        sa.Column(
            "provider",
            sa.Enum("STRIPE", "PAYPAL", name="billingsourceprovider"),
            nullable=True,
        ),
        schema="Billing",
    )
    op.drop_index(
        op.f("Credits_uuid_idx"), table_name="Credits", schema="Billing"
    )
    op.drop_column("Credits", "uuid", schema="Billing")
    op.drop_column("Credits", "id", schema="Billing")
    op.drop_column("Credits", "name", schema="Billing")
    op.drop_column("Credits", "note", schema="Billing")
    op.drop_column("Credits", "expired_date", schema="Billing")
    op.drop_column("Credits", "current_spent", schema="Billing")
    op.drop_column("Credits", "start_date", schema="Billing")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "27e4b090ceec_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Credits",
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
        schema="Billing",
    )
    op.add_column(
        "Credits",
        sa.Column(
            "current_spent",
            sa.NUMERIC(precision=18, scale=8),
            autoincrement=False,
            nullable=False,
        ),
        schema="Billing",
    )
    op.add_column(
        "Credits",
        sa.Column(
            "expired_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        schema="Billing",
    )
    op.add_column(
        "Credits",
        sa.Column(
            "note", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
        schema="Billing",
    )
    op.add_column(
        "Credits",
        sa.Column(
            "name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        schema="Billing",
    )
    op.add_column(
        "Credits",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        schema="Billing",
    )
    op.add_column(
        "Credits",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        schema="Billing",
    )
    op.create_index(
        op.f("Credits_uuid_idx"),
        "Credits",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    op.drop_column("BillingInvoices", "provider", schema="Billing")
    op.drop_index(
        op.f("CreditTransactions_organization_id_idx"),
        table_name="CreditTransactions",
        schema="Billing",
    )
    op.drop_table("CreditTransactions", schema="Billing")
    # ### end Alembic commands ###
