"""message

Revision ID: 2abf94d9e843
Revises: a23008f03941
Create Date: 2026-02-27 11:18:24.247252
Feature:
Reason:

"""
from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2abf94d9e843'
down_revision: Union[str, Sequence[str], None] = 'a23008f03941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent

def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")

def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "2abf94d9e843_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Messages', 'timestamp', schema='Conversation')
    op.add_column('Messages', sa.Column('timestamp', sa.DateTime(),nullable=False), schema='Conversation')
    op.drop_column('Messages', 'updated_at', schema='Conversation')
    op.drop_column('Messages', 'created_at', schema='Conversation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "2abf94d9e843_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='Conversation')
    op.add_column('Messages', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='Conversation')
    op.alter_column('Messages', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True,
               schema='Conversation')
    # ### end Alembic commands ###
