"""conversation

Revision ID: 3e33884f6b05
Revises: 23c4153d35e9
Create Date: 2026-02-28 11:53:38.172843
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e33884f6b05"
down_revision: Union[str, Sequence[str], None] = "23c4153d35e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "3e33884f6b05_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Conversations",
        sa.Column(
            "extra_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        schema="Conversation",
    )
    op.add_column(
        "Files",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        schema="FileStorage",
    )
    op.create_index(
        op.f("Files_project_id_idx"),
        "Files",
        ["project_id"],
        unique=False,
        schema="FileStorage",
    )
    op.create_foreign_key(
        op.f("Files_project_id_fkey"),
        "Files",
        "Projects",
        ["project_id"],
        ["id"],
        source_schema="FileStorage",
        referent_schema="Project",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "3e33884f6b05_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("Files_project_id_fkey"),
        "Files",
        schema="FileStorage",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("Files_project_id_idx"), table_name="Files", schema="FileStorage"
    )
    op.drop_column("Files", "project_id", schema="FileStorage")
    op.drop_column("Conversations", "extra_metadata", schema="Conversation")
    # ### end Alembic commands ###
