"""project_and_file_and_conversation

Revision ID: 6dfe5f2fd7ff
Revises: 909c37558b63
Create Date: 2026-01-26 08:56:48.526142
Feature:
Reason:

"""
from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dfe5f2fd7ff'
down_revision: Union[str, Sequence[str], None] = '909c37558b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent

def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")

def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "6dfe5f2fd7ff_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS \"Project\";")
    op.execute("CREATE SCHEMA IF NOT EXISTS \"FileStorage\";")
    op.execute("CREATE SCHEMA IF NOT EXISTS \"Conversation\";")
    op.create_table('Conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Conversations_pkey')),
    schema='Conversation'
    )
    op.create_index(op.f('Conversations_project_id_idx'), 'Conversations', ['project_id'], unique=False, schema='Conversation')
    op.create_index(op.f('Conversations_uuid_idx'), 'Conversations', ['uuid'], unique=True, schema='Conversation')
    op.create_table('Messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Messages_pkey')),
    schema='Conversation'
    )
    op.create_table('Files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('filetype', sa.String(length=64), nullable=False),
    sa.Column('size_in_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Files_pkey')),
    schema='FileStorage'
    )
    op.create_index(op.f('Files_uuid_idx'), 'Files', ['uuid'], unique=True, schema='FileStorage')
    op.create_table('Projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Projects_pkey')),
    schema='Project'
    )
    op.create_index(op.f('Projects_uuid_idx'), 'Projects', ['uuid'], unique=True, schema='Project')
    op.add_column('ApiKeys', sa.Column('project_id', sa.BigInteger(), nullable=False), schema='ApiKey')
    op.create_index(op.f('ApiKeys_project_id_idx'), 'ApiKeys', ['project_id'], unique=False, schema='ApiKey')
    op.create_foreign_key(op.f('ApiKeys_project_id_fkey'), 'ApiKeys', 'Projects', ['project_id'], ['id'], source_schema='ApiKey', referent_schema='Project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "6dfe5f2fd7ff_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ApiKeys_project_id_fkey'), 'ApiKeys', schema='ApiKey', type_='foreignkey')
    op.drop_index(op.f('ApiKeys_project_id_idx'), table_name='ApiKeys', schema='ApiKey')
    op.drop_column('ApiKeys', 'project_id', schema='ApiKey')
    op.drop_index(op.f('Projects_uuid_idx'), table_name='Projects', schema='Project')
    op.drop_table('Projects', schema='Project')
    op.drop_index(op.f('Files_uuid_idx'), table_name='Files', schema='FileStorage')
    op.drop_table('Files', schema='FileStorage')
    op.drop_table('Messages', schema='Conversation')
    op.drop_index(op.f('Conversations_uuid_idx'), table_name='Conversations', schema='Conversation')
    op.drop_index(op.f('Conversations_project_id_idx'), table_name='Conversations', schema='Conversation')
    op.drop_table('Conversations', schema='Conversation')
    # ### end Alembic commands ###
