"""rag

Revision ID: 778951e24058
Revises: 893f07fc924c
Create Date: 2026-04-21 09:15:32.549681
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "778951e24058"
down_revision: Union[str, Sequence[str], None] = "893f07fc924c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "Rag"')

    op.create_table(
        "Metadata",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["FileStorage.Files.id"],
            name=op.f("Metadata_file_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["Project.Projects.id"],
            name=op.f("Metadata_project_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("Metadata_pkey")),
        sa.UniqueConstraint("file_id", name=op.f("Metadata_file_id_uq")),
        schema="Rag",
    )
    op.create_index(
        op.f("Metadata_project_id_idx"),
        "Metadata",
        ["project_id"],
        unique=False,
        schema="Rag",
    )
    op.drop_index(
        op.f("SpendingLimits_organization_id_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("SpendingLimits_project_id_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("SpendingLimits_uuid_idx"),
        table_name="SpendingLimits",
        schema="Billing",
    )
    op.drop_index(
        op.f("ix_spending_limits_org"),
        table_name="SpendingLimits",
        schema="Billing",
        postgresql_where="(project_id IS NULL)",
    )
    op.drop_table("SpendingLimits", schema="Billing")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "SpendingLimits",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "organization_id",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "project_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "limit_type",
            postgresql.ENUM(
                "MONTHLY", name="spendinglimittype", schema="Billing"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "limit",
            sa.NUMERIC(precision=18, scale=8),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("SpendingLimits_pkey")),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            name=op.f("uq_spending_limit"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema="Billing",
    )
    op.create_index(
        op.f("ix_spending_limits_org"),
        "SpendingLimits",
        ["organization_id"],
        unique=True,
        schema="Billing",
        postgresql_where="(project_id IS NULL)",
    )
    op.create_index(
        op.f("SpendingLimits_uuid_idx"),
        "SpendingLimits",
        ["uuid"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_project_id_idx"),
        "SpendingLimits",
        ["project_id"],
        unique=True,
        schema="Billing",
    )
    op.create_index(
        op.f("SpendingLimits_organization_id_idx"),
        "SpendingLimits",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    op.drop_index(
        op.f("Metadata_project_id_idx"), table_name="Metadata", schema="Rag"
    )
    op.drop_table("Metadata", schema="Rag")
    # ### end Alembic commands ###
