"""billing

Revision ID: 7dbe206afcb5
Revises: 91eaac7c7c94
Create Date: 2026-04-10 11:34:13.734116
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7dbe206afcb5"
down_revision: Union[str, Sequence[str], None] = "91eaac7c7c94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "7dbe206afcb5_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "BillingInvoices",
        "provider_invoice_id",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
        schema="Billing",
    )
    op.drop_constraint(
        op.f("BillingInvoices_billing_period_uq"),
        "BillingInvoices",
        schema="Billing",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_org_billing_period",
        "BillingInvoices",
        ["organization_id", "billing_period"],
        schema="Billing",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "7dbe206afcb5_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_org_billing_period",
        "BillingInvoices",
        schema="Billing",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("BillingInvoices_billing_period_uq"),
        "BillingInvoices",
        ["billing_period"],
        schema="Billing",
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "BillingInvoices",
        "provider_invoice_id",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
        schema="Billing",
    )
    # ### end Alembic commands ###
