"""billing

Revision ID: 91eaac7c7c94
Revises: 3fd4a6c3d55a
Create Date: 2026-04-10 09:47:52.022200
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "91eaac7c7c94"
down_revision: Union[str, Sequence[str], None] = "3fd4a6c3d55a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "91eaac7c7c94_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("BillingSources_organization_id_idx"),
        table_name="BillingSources",
        schema="Billing",
    )
    op.create_index(
        op.f("BillingSources_organization_id_idx"),
        "BillingSources",
        ["organization_id"],
        unique=True,
        schema="Billing",
    )
    op.drop_column("BillingSources", "status", schema="Billing")
    op.create_index(
        op.f("BillingTransactions_status_idx"),
        "BillingTransactions",
        ["status"],
        unique=False,
        schema="Billing",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "91eaac7c7c94_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("BillingTransactions_status_idx"),
        table_name="BillingTransactions",
        schema="Billing",
    )
    op.add_column(
        "BillingSources",
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "ACTIVE", "DELETED", name="billingsourcestate"
            ),
            server_default=sa.text("'PENDING'::billingsourcestate"),
            autoincrement=False,
            nullable=False,
        ),
        schema="Billing",
    )
    op.drop_index(
        op.f("BillingSources_organization_id_idx"),
        table_name="BillingSources",
        schema="Billing",
    )
    op.create_index(
        op.f("BillingSources_organization_id_idx"),
        "BillingSources",
        ["organization_id"],
        unique=False,
        schema="Billing",
    )
    # ### end Alembic commands ###
