"""Auth: First revision

Revision ID: 981f16f3d280
Revises:
Create Date: 2025-12-02 21:57:39.453276
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "981f16f3d280"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Permissions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("name", "id", name=op.f("Permissions_pkey")),
        sa.UniqueConstraint("name", name=op.f("Permissions_name_uq")),
        schema="Auth",
    )
    op.create_index(
        op.f("idx_Auth_Permissions_uuid"),
        "Permissions",
        ["uuid"],
        unique=True,
        schema="Auth",
    )
    op.create_table(
        "USERS",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("USERS_pkey")),
        sa.UniqueConstraint("email", name=op.f("USERS_email_uq")),
        sa.UniqueConstraint("username", name=op.f("USERS_username_uq")),
        schema="Auth",
    )
    op.create_index(
        op.f("idx_Auth_USERS_uuid"),
        "USERS",
        ["uuid"],
        unique=True,
        schema="Auth",
    )
    op.create_table(
        "ApiKeys",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("hashed_key", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["Auth.USERS.id"], name=op.f("ApiKeys_owner_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ApiKeys_pkey")),
        sa.UniqueConstraint("hashed_key", name=op.f("ApiKeys_hashed_key_uq")),
        schema="Auth",
    )
    op.create_index(
        op.f("idx_Auth_ApiKeys_uuid"),
        "ApiKeys",
        ["uuid"],
        unique=True,
        schema="Auth",
    )
    op.create_table(
        "ApiKeyPermissions",
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("permission_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["Auth.ApiKeys.id"],
            name=op.f("ApiKeyPermissions_api_key_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_name"],
            ["Auth.Permissions.name"],
            name=op.f("ApiKeyPermissions_permission_name_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "api_key_id", "permission_name", name=op.f("ApiKeyPermissions_pkey")
        ),
        schema="Auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ApiKeyPermissions", schema="Auth")
    op.drop_index(
        op.f("idx_Auth_ApiKeys_uuid"), table_name="ApiKeys", schema="Auth"
    )
    op.drop_table("ApiKeys", schema="Auth")
    op.drop_index(
        op.f("idx_Auth_USERS_uuid"), table_name="USERS", schema="Auth"
    )
    op.drop_table("USERS", schema="Auth")
    op.drop_index(
        op.f("idx_Auth_Permissions_uuid"),
        table_name="Permissions",
        schema="Auth",
    )
    op.drop_table("Permissions", schema="Auth")
    # ### end Alembic commands ###
