"""auth_v1

Revision ID: 9a2f25266d11
Revises:
Create Date: 2025-12-03 11:55:40.417003
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a2f25266d11"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE SCHEMA IF NOT EXISTS "Auth";')
    op.create_table(
        "Permissions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("Permissions_pkey")),
        sa.UniqueConstraint("name", name=op.f("Permissions_name_uq")),
        schema="Auth",
    )
    op.create_table(
        "Users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("Users_pkey")),
        sa.UniqueConstraint("email", name=op.f("Users_email_uq")),
        sa.UniqueConstraint("uid", name=op.f("Users_uid_uq")),
        sa.UniqueConstraint("username", name=op.f("Users_username_uq")),
        schema="Auth",
    )
    op.create_table(
        "ApiKeys",
        sa.Column("owner_id", sa.BIGINT(), nullable=False),
        sa.Column("hashed_key", sa.String(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uid",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["Auth.Users.id"], name=op.f("ApiKeys_owner_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ApiKeys_pkey")),
        sa.UniqueConstraint("hashed_key", name=op.f("ApiKeys_hashed_key_uq")),
        sa.UniqueConstraint("uid", name=op.f("ApiKeys_uid_uq")),
        schema="Auth",
    )
    op.create_table(
        "ApiKeyPermissions",
        sa.Column("api_key_id", sa.BIGINT(), nullable=False),
        sa.Column("permission_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["Auth.ApiKeys.id"],
            name=op.f("ApiKeyPermissions_api_key_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_name"],
            ["Auth.Permissions.name"],
            name=op.f("ApiKeyPermissions_permission_name_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "api_key_id", "permission_name", name=op.f("ApiKeyPermissions_pkey")
        ),
        schema="Auth",
    )
    op.create_index(
        op.f("idx_Auth_ApiKeyPermissions_api_key_id"),
        "ApiKeyPermissions",
        ["api_key_id"],
        unique=False,
        schema="Auth",
    )
    op.create_index(
        op.f("idx_Auth_ApiKeyPermissions_permission_name"),
        "ApiKeyPermissions",
        ["permission_name"],
        unique=False,
        schema="Auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_Auth_ApiKeyPermissions_permission_name"),
        table_name="ApiKeyPermissions",
        schema="Auth",
    )
    op.drop_index(
        op.f("idx_Auth_ApiKeyPermissions_api_key_id"),
        table_name="ApiKeyPermissions",
        schema="Auth",
    )
    op.drop_table("ApiKeyPermissions", schema="Auth")
    op.drop_table("ApiKeys", schema="Auth")
    op.drop_table("Users", schema="Auth")
    op.drop_table("Permissions", schema="Auth")
    op.execute('DROP SCHEMA IF EXISTS "Auth" CASCADE;')
    # ### end Alembic commands ###
