"""file_storage

Revision ID: a23008f03941
Revises: bc3ad7bfcbee
Create Date: 2026-02-26 21:22:08.944336
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a23008f03941"
down_revision: Union[str, Sequence[str], None] = "bc3ad7bfcbee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "a23008f03941_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE FileStatus AS ENUM ('UPLOADING', 'AVAILABLE', 'DELETED');"
    )
    op.add_column(
        "Files",
        sa.Column(
            "status",
            sa.Enum("UPLOADING", "AVAILABLE", "DELETED", name="filestatus"),
            nullable=False,
        ),
        schema="FileStorage",
    )
    op.drop_column("Files", "file_type", schema="FileStorage")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "a23008f03941_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Files",
        sa.Column(
            "file_type",
            postgresql.ENUM(
                "IMAGE",
                "DOCUMENT",
                "AUDIO",
                "VIDEO",
                "GENERAL",
                name="filetype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        schema="FileStorage",
    )
    op.drop_column("Files", "status", schema="FileStorage")
    # ### end Alembic commands ###
