"""conversation_message_update

Revision ID: bc3ad7bfcbee
Revises: 0091936a904e
Create Date: 2026-02-06 21:13:54.638383
Feature:
Reason:

"""
from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bc3ad7bfcbee'
down_revision: Union[str, Sequence[str], None] = '0091936a904e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent

def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")

def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "bc3ad7bfcbee_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE filetype AS ENUM ('IMAGE', 'DOCUMENT', 'AUDIO', 'VIDEO', 'GENERAL');")
    op.add_column('Files', sa.Column('mime_type', sa.String(length=64), nullable=False), schema='FileStorage')
    op.add_column('Files', sa.Column('file_type', sa.Enum('IMAGE', 'DOCUMENT', 'AUDIO', 'VIDEO', 'GENERAL', name='filetype'), nullable=False), schema='FileStorage')
    op.drop_column('Files', 'filetype', schema='FileStorage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "bc3ad7bfcbee_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Files', sa.Column('filetype', sa.VARCHAR(length=64), autoincrement=False, nullable=False), schema='FileStorage')
    op.drop_column('Files', 'file_type', schema='FileStorage')
    op.drop_column('Files', 'mime_type', schema='FileStorage')
    # ### end Alembic commands ###
