"""billing

Revision ID: e12c66752b92
Revises: 27e4b090ceec
Create Date: 2026-04-13 12:06:43.247794
Feature:
Reason:

"""

from alembic import op

from typing import Union, Sequence
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e12c66752b92"
down_revision: Union[str, Sequence[str], None] = "27e4b090ceec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "e12c66752b92_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "BillingInvoices",
        sa.Column("refunded_at", sa.DateTime(), nullable=True),
        schema="Billing",
    )
    op.create_unique_constraint(
        "uq_provider_invoice",
        "BillingInvoices",
        ["provider", "provider_invoice_id"],
        schema="Billing",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "e12c66752b92_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_provider_invoice",
        "BillingInvoices",
        schema="Billing",
        type_="unique",
    )
    op.drop_column("BillingInvoices", "refunded_at", schema="Billing")
    # ### end Alembic commands ###
