"""conversation

Revision ID: f4f3c8919bfa
Revises: 3e33884f6b05
Create Date: 2026-03-05 16:09:15.048113
Feature:
Reason:

"""

from alembic import op

from typing import Sequence, Union
from pathlib import Path

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4f3c8919bfa"
down_revision: Union[str, Sequence[str], None] = "3e33884f6b05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

script_path = Path(__file__).resolve()
script_directory = script_path.parent


def executeScript(script: str):
    statements = script.split(";")
    for statement in statements:
        stmt = statement.strip()
        if stmt not in ["BEGIN", "END", "COMMIT"]:
            op.execute(stmt + ";")


def upgrade() -> None:
    """Upgrade schema."""
    path = script_directory / "f4f3c8919bfa_upgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Conversations", "title", schema="Conversation")
    op.drop_constraint(
        op.f("Messages_conversation_id_fkey"),
        "Messages",
        schema="Conversation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("Messages_conversation_id_fkey"),
        "Messages",
        "Conversations",
        ["conversation_id"],
        ["id"],
        source_schema="Conversation",
        referent_schema="Conversation",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    path = script_directory / "f4f3c8919bfa_downgrade.sql"
    if path.exists():
        with open(path) as f:
            sql = f.read()
        executeScript(sql)
    else:
        open(path, "w")
        # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("Messages_conversation_id_fkey"),
        "Messages",
        schema="Conversation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("Messages_conversation_id_fkey"),
        "Messages",
        "Conversations",
        ["conversation_id"],
        ["id"],
        source_schema="Conversation",
        referent_schema="Conversation",
    )
    op.add_column(
        "Conversations",
        sa.Column(
            "title", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        schema="Conversation",
    )
    # ### end Alembic commands ###
