@baseUrl=http://localhost:8001/api/v2

# Test your FastAPI endpoints

POST {{baseUrl}}/auth/email-register
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "123456"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "123456"
}

> {%
 client.global.set("access_token", response.body.access_token)
 %}

###
POST {{baseUrl}}/api_keys/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "permissions": ["test-permission-1"]
}

> {%
 client.global.set("api_key", response.body.api_key)
 %}

###
GET {{baseUrl}}/test/
X-API-Key: {{api_key}}

###
GET {{baseUrl}}/test/admin
X-API-Key: {{api_key}}