"""billing_source

Revision ID: 2759711a45ad
Revises: 5522a77606bc
Create Date: 2026-04-06 20:56:23.319011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2759711a45ad'
down_revision: Union[str, Sequence[str], None] = '5522a77606bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('BillingSources_organization_id_idx'), table_name='BillingSources', schema='Billing')
    op.create_index(op.f('BillingSources_organization_id_idx'), 'BillingSources', ['organization_id'], unique=True, schema='Billing')
    op.drop_column('BillingSources', 'status', schema='Billing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BillingSources', sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'DELETED', name='billingsourcestate'), server_default=sa.text("'PENDING'::billingsourcestate"), autoincrement=False, nullable=False), schema='Billing')
    op.drop_index(op.f('BillingSources_organization_id_idx'), table_name='BillingSources', schema='Billing')
    op.create_index(op.f('BillingSources_organization_id_idx'), 'BillingSources', ['organization_id'], unique=False, schema='Billing')
    # ### end Alembic commands ###
