"""billing

Revision ID: cce57f392192
Revises: 85052901f85f
Create Date: 2026-03-31 21:32:51.370765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cce57f392192'
down_revision: Union[str, Sequence[str], None] = '85052901f85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BillingSources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.Enum('STRIPE', 'PAYPAL', name='billingsourceprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DELETED', name='billingsourcestate'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('BillingSources_pkey')),
    schema='Billing'
    )
    op.create_index(op.f('BillingSources_organization_id_idx'), 'BillingSources', ['organization_id'], unique=False, schema='Billing')
    op.create_index(op.f('BillingSources_uuid_idx'), 'BillingSources', ['uuid'], unique=True, schema='Billing')
    op.drop_index(op.f('BillingSources_organization_id_idx'), table_name='BillingSources')
    op.drop_index(op.f('BillingSources_uuid_idx'), table_name='BillingSources')
    op.drop_table('BillingSources')
    op.add_column('BillingInvoices', sa.Column('provider_invoice_id', sa.String(length=128), nullable=False), schema='Billing')
    op.add_column('BillingTransactions', sa.Column('captured_at', sa.DateTime(), nullable=True), schema='Billing')
    op.drop_index(op.f('BillingTransactions_created_at_idx'), table_name='BillingTransactions', schema='Billing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('BillingTransactions_uuid_idx'), table_name='BillingTransactions', schema='Billing')
    op.create_index(op.f('BillingTransactions_created_at_idx'), 'BillingTransactions', [sa.literal_column('created_at DESC')], unique=False, schema='Billing')
    op.drop_column('BillingTransactions', 'captured_at', schema='Billing')
    op.drop_column('BillingInvoices', 'provider_invoice_id', schema='Billing')
    op.create_table('BillingSources',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('BillingSources_pkey')),
    sa.UniqueConstraint('organization_id', 'source_type', name=op.f('uq_billing_source'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('BillingSources_uuid_idx'), 'BillingSources', ['uuid'], unique=True)
    op.create_index(op.f('BillingSources_organization_id_idx'), 'BillingSources', ['organization_id'], unique=False)
    op.drop_index(op.f('BillingSources_uuid_idx'), table_name='BillingSources', schema='Billing')
    op.drop_index(op.f('BillingSources_organization_id_idx'), table_name='BillingSources', schema='Billing')
    op.drop_table('BillingSources', schema='Billing')
    # ### end Alembic commands ###
