"""billing

Revision ID: ddada74c8edf
Revises: 
Create Date: 2026-03-20 22:13:50.214791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddada74c8edf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        text("""CREATE SCHEMA IF NOT EXISTS "Billing";""")
    )

    op.create_table('BillingInvoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('billing_period', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('used_credits', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('BillingInvoices_pkey')),
    sa.UniqueConstraint('billing_period', name=op.f('BillingInvoices_billing_period_uq')),
    schema='Billing'
    )
    op.create_index(op.f('BillingInvoices_organization_id_idx'), 'BillingInvoices', ['organization_id'], unique=False, schema='Billing')
    op.create_index(op.f('BillingInvoices_uuid_idx'), 'BillingInvoices', ['uuid'], unique=True, schema='Billing')
    op.create_table('BillingTransactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('apikey_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('BillingTransactions_pkey')),
    schema='Billing'
    )
    op.create_index(op.f('BillingTransactions_apikey_id_idx'), 'BillingTransactions', ['apikey_id'], unique=False, schema='Billing')
    op.create_index(op.f('BillingTransactions_organization_id_idx'), 'BillingTransactions', ['organization_id'], unique=False, schema='Billing')
    op.create_index(op.f('BillingTransactions_project_id_idx'), 'BillingTransactions', ['project_id'], unique=False, schema='Billing')
    # op.create_index(op.f('BillingTransactions_uuid_idx'), 'BillingTransactions', ['uuid'], unique=True, schema='Billing')
    op.create_table('Credits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expired_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_spent', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Credits_pkey')),
    schema='Billing'
    )
    op.create_index(op.f('Credits_organization_id_idx'), 'Credits', ['organization_id'], unique=False, schema='Billing')
    op.create_index(op.f('Credits_uuid_idx'), 'Credits', ['uuid'], unique=True, schema='Billing')
    op.create_table('BillingSources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('BillingSources_pkey')),
    sa.UniqueConstraint('organization_id', 'source_type', name='uq_billing_source')
    )
    op.create_index(op.f('BillingSources_organization_id_idx'), 'BillingSources', ['organization_id'], unique=False)
    op.create_index(op.f('BillingSources_uuid_idx'), 'BillingSources', ['uuid'], unique=True)
    op.create_table('SpendingLimits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('limit_type', sa.Enum('MONTHLY', 'DAILY', name='spendinglimittype', schema='Billing'), nullable=False),
    sa.Column('limit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('SpendingLimits_pkey')),
    sa.UniqueConstraint('organization_id', 'project_id', name='uq_spending_limit')
    )
    op.create_index(op.f('SpendingLimits_organization_id_idx'), 'SpendingLimits', ['organization_id'], unique=False)
    op.create_index(op.f('SpendingLimits_project_id_idx'), 'SpendingLimits', ['project_id'], unique=True)
    op.create_index(op.f('SpendingLimits_uuid_idx'), 'SpendingLimits', ['uuid'], unique=True)
    op.create_index('ix_spending_limits_org', 'SpendingLimits', ['organization_id'], unique=True, postgresql_where=sa.text('project_id IS NULL'))
    op.create_table('BillingInvoiceLineItems',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['Billing.BillingInvoices.id'], name=op.f('BillingInvoiceLineItems_invoice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('BillingInvoiceLineItems_pkey')),
    schema='Billing'
    )
    op.create_index(op.f('BillingInvoiceLineItems_invoice_id_idx'), 'BillingInvoiceLineItems', ['invoice_id'], unique=False, schema='Billing')
    op.create_index(op.f('BillingInvoiceLineItems_project_id_idx'), 'BillingInvoiceLineItems', ['project_id'], unique=False, schema='Billing')
    op.create_index(op.f('BillingInvoiceLineItems_uuid_idx'), 'BillingInvoiceLineItems', ['uuid'], unique=True, schema='Billing')
    # ### end Alembic commands ###
    op.execute(
        text("""
            SELECT create_hypertable('"Billing"."BillingTransactions"', 'created_at', 
        chunk_time_interval => INTERVAL '7 days');
            """
             ))

    op.execute(
        text("""
             ALTER TABLE "Billing"."BillingTransactions" SET (
                 timescaledb.compress,
                 timescaledb.compress_segmentby = 'apikey_id, project_id, organization_id',
                 timescaledb.compress_orderby = 'created_at DESC'
                 );
 """))


    op.execute(
        text("""
             SELECT add_compression_policy('"Billing"."BillingTransactions"', INTERVAL '14 days');
             """))

    op.execute(
        text("""
    CREATE MATERIALIZED VIEW "Billing".daily_billing_summary
    WITH (timescaledb.continuous) AS
    SELECT 
        time_bucket('1 day', created_at) AS bucket,
        apikey_id,
        SUM(amount) AS total_amount,
        COUNT(*) AS transaction_count
    FROM "Billing"."BillingTransactions"
    GROUP BY bucket, apikey_id
    with no data;
    """)
    )
    op.execute(
        text("""
    SELECT add_continuous_aggregate_policy('"Billing".daily_billing_summary',
        start_offset => INTERVAL '3 days',
        end_offset => INTERVAL '0 seconds',
        schedule_interval => INTERVAL '1 hour');
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('BillingInvoiceLineItems_uuid_idx'), table_name='BillingInvoiceLineItems', schema='Billing')
    op.drop_index(op.f('BillingInvoiceLineItems_project_id_idx'), table_name='BillingInvoiceLineItems', schema='Billing')
    op.drop_index(op.f('BillingInvoiceLineItems_invoice_id_idx'), table_name='BillingInvoiceLineItems', schema='Billing')
    op.drop_table('BillingInvoiceLineItems', schema='Billing')
    op.drop_index('ix_spending_limits_org', table_name='SpendingLimits', postgresql_where=sa.text('project_id IS NULL'))
    op.drop_index(op.f('SpendingLimits_uuid_idx'), table_name='SpendingLimits')
    op.drop_index(op.f('SpendingLimits_project_id_idx'), table_name='SpendingLimits')
    op.drop_index(op.f('SpendingLimits_organization_id_idx'), table_name='SpendingLimits')
    op.drop_table('SpendingLimits')
    op.drop_index(op.f('BillingSources_uuid_idx'), table_name='BillingSources')
    op.drop_index(op.f('BillingSources_organization_id_idx'), table_name='BillingSources')
    op.drop_table('BillingSources')
    op.drop_index(op.f('Credits_uuid_idx'), table_name='Credits', schema='Billing')
    op.drop_index(op.f('Credits_organization_id_idx'), table_name='Credits', schema='Billing')
    op.drop_table('Credits', schema='Billing')
    op.drop_index(op.f('BillingTransactions_uuid_idx'), table_name='BillingTransactions', schema='Billing')
    op.drop_index(op.f('BillingTransactions_project_id_idx'), table_name='BillingTransactions', schema='Billing')
    op.drop_index(op.f('BillingTransactions_organization_id_idx'), table_name='BillingTransactions', schema='Billing')
    op.drop_index(op.f('BillingTransactions_apikey_id_idx'), table_name='BillingTransactions', schema='Billing')
    op.drop_table('BillingTransactions', schema='Billing')
    op.drop_index(op.f('BillingInvoices_uuid_idx'), table_name='BillingInvoices', schema='Billing')
    op.drop_index(op.f('BillingInvoices_organization_id_idx'), table_name='BillingInvoices', schema='Billing')
    op.drop_table('BillingInvoices', schema='Billing')
    # ### end Alembic commands ###

